### ISSUE TITLE
Semver is not applicable with latest Cordova-CLI dev versions

### ISSUE THREAD

**Issue by TankMasterRL** [driftyco/ionic-app-lib#10]
Hello!

I received this error today after updating Ionic-CLI to v1.6.0:
```
TypeError: Invalid Version: 5.1.2-dev (cordova-lib@5.1.2-dev)
    at new SemVer (C:\Users\tank-_000\AppData\Roaming\npm\node_modules\ionic\nod
e_modules\semver\semver.js:295:11)
    at Range.test (C:\Users\tank-_000\AppData\Roaming\npm\node_modules\ionic\nod
e_modules\semver\semver.js:1049:15)
    at Function.satisfies (C:\Users\tank-_000\AppData\Roaming\npm\node_modules\i
onic\node_modules\semver\semver.js:1098:16)
    at Object.checkRuntime (C:\Users\tank-_000\AppData\Roaming\npm\node_modules\
ionic\node_modules\ionic-app-lib\lib\info.js:295:32)
    at Object.run (C:\Users\tank-_000\AppData\Roaming\npm\node_modules\ionic\lib
\cli.js:54:10)
    at Object.<anonymous> (C:\Users\tank-_000\AppData\Roaming\npm\node_modules\i
onic\bin\ionic:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Invalid Version: 5.1.2-dev (cordova-lib@5.1.2-dev) (CLI v1.6.0)
    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```
I need to use v5.1.2-dev because of this error: https://issues.apache.org/jira/browse/CB-9212.
I know that the issue lies at Apache for not following the semver specification, so I created an issue at them today. https://issues.apache.org/jira/browse/CB-9290
Hopefully they will agree to the change so these errors can be avoided in the future.

Best regards,
Robin

**Comment by jbavari** [comment]
@TankMasterRL how did you install the CLI version? By git cloning?

If you git cloned and npm link'ed, can you manually change the package.json to remove the `-dev`?

**Comment by TankMasterRL** [comment]
Yes I did, and I tested the method you described successfully. Though the whole idea with a package manager disappears then, at least for me.
