### ISSUE TITLE
[PATCH] Upload: Wrong ZIP File when DocumentRoot Ends with a Slash or is Absolute

### ISSUE THREAD

**Issue by phible** [driftyco/ionic-app-lib#34]
I have the following in my `ionic.project`:
```
{
  "documentRoot": "www/"
}
```

**Note that trailing slash**. 

`ionic upload` will generate the full name of the ZIP file (the `www.zip`) as:
```
/full/path/to/project/www/.zip
```

After the ZIP has been _successfully_ created (as `www/.zip`), the uploading code will try to locate it in
```
/full/path/to/project/www.zip
```
and will fail, with an error message like this:

```
phil@otr% ionic upload
Uploading app....
An error occurred uploading the build: Error: ENOENT: no such file or directory, open '/path/to/app/www.zip'

Error: ENOENT: no such file or directory, open '/path/to/app/www.zip'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.uploadToS3 (/home/phil/opt/n/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:112:14)
    at /home/phil/opt/n/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:56:21
    at _fulfilled (/home/phil/opt/n/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/phil/opt/n/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/phil/opt/n/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /home/phil/opt/n/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/home/phil/opt/n/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)

ENOENT: no such file or directory, open '/path/to/app/www.zip' (CLI v1.7.0)
```

The problem is how the ZIP file's path is generated in `ionic-app-lib/lib/upload.js`:

```javascript
Utils.createArchive = function(appDirectory, documentRoot) {
  // ...
  var zipPath = path.join(appDirectory, documentRoot);
  // ...
  var zipDestination = zipPath + ".zip"
  // ...
}
```
`path.join()` will correctly concatenate the paths, but it won't remove the trailing slash.  Furthermore, the would be also wrong if `DocumentRoot` specified in `ionic.project` is an absolute path.

The correct solution is to use `path.resolve`:
```
--- /home/phil/src/ionic/ionic-app-lib.git/lib/utils.js
+++ /home/phil/opt/n/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js
@@ -49,7 +51,7 @@
  */
 Utils.createArchive = function(appDirectory, documentRoot) {
   var q = Q.defer();
-  var zipPath = path.join(appDirectory, documentRoot);
+  var zipPath = path.resolve(appDirectory, documentRoot);
 
   logging.logger.debug('Now zipping contents of ' + zipPath);
 
@@ -57,7 +59,8 @@
     q.reject(documentRoot + ' directory cannot be found. Make sure the working directory is at the top level of an Ionic project.', 'upload');
   }
 
-  var zipDestination = zipPath + ".zip"
+  var zipDestination = path.join(zipPath + ".zip");
+  logging.logger.debug('ZIP file: ' + zipDestination);
   var zip = fs.createWriteStream(zipDestination);
 
   var archive = archiver('zip');
```

**Comment by lewisl9029** [comment]
Somewhat related issue I ran into: 

It simply doesn't work when using a custom documentRoot other than 'www', because it looks like the expected filename is hardcoded to 'www.zip'(https://github.com/driftyco/ionic-app-lib/blob/master/lib/upload.js#L17), while the generated zip uses documentRoot for the filename (https://github.com/driftyco/ionic-app-lib/blob/master/lib/upload.js#L36).

Here's the full error I received: 

```
An error occurred uploading the build: Error: ENOENT: no such file or directory, open '/toc/www.zip'

Error: ENOENT: no such file or directory, open '/toc/www.zip'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.uploadToS3 (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:112:14)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:56:21
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

ENOENT: no such file or directory, open '/toc/www.zip' (CLI v1.7.1)
```

**Comment by agustinhaller** [comment]
I'm experiencing the same as @lewisl9029 with `ionic upload` command.

``` bash
Uploading app....
An error occurred uploading the build: Error: ENOENT, no such file or directory '/Users/agustinhaller/IonicThemes/ionProfiles/1/www.zip'

....

at Object.uploadToS3 (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:112:14)
at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:56:21
```

I'm using
Ionic CLI Version: 1.7.6
Ionic App Lib Version: 0.6.2

@jbavari @Fuiste @dwieeb @jccf091 @ericb any updates on this?

**Comment by nahankid** [comment]
Ditto!
