### ISSUE TITLE
[io-config] explicit error message for corrupted file?

### ISSUE THREAD

**Issue by bamarni** [driftyco/ionic-app-lib#82]
When trying to upload an app to ionic view I had this error :
```
> ionic upload
Uploading app....
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/io-config.js:179:28
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

Turned out that my `.io-config.json` file was empty so couldn't be parsed, after removing it it worked. Would it make sense to have a more explicit error message here, or is it an edge case? It's a project I took over so probably they emptied the file manually for privacy reasons.

**Comment by tlancina** [comment]
Yeah definitely should be a more helpful error there. The configuration for both project and platform services is being consolidated in ionic.config.json, and as part of that we'll be improving the logging and error messages.

**Comment by bamarni** [comment]
nice :) feel free to close if it's already in your pipeline
